# Light source block IDs for colored block lighting (mc_Entity.x)

block.1 = minecraft:torch minecraft:wall_torch
block.2 = minecraft:lantern
block.3 = minecraft:soul_torch minecraft:soul_wall_torch
block.4 = minecraft:glowstone minecraft:shroomlight
block.5 = minecraft:sea_lantern
block.6 = minecraft:lava
block.7 = minecraft:fire minecraft:soul_fire minecraft:campfire:lit=true minecraft:soul_campfire:lit=true
block.8 = minecraft:magma_block
block.9 = minecraft:end_rod
block.10 = minecraft:sea_pickle
block.11 = minecraft:redstone_torch minecraft:redstone_wall_torch minecraft:redstone_lamp:lit=true minecraft:lit_redstone_ore
block.12 = minecraft:jack_o_lantern
block.13 = minecraft:crying_obsidian minecraft:respawn_anchor
block.14 = minecraft:amethyst_cluster minecraft:large_amethyst_bud minecraft:medium_amethyst_bud minecraft:small_amethyst_bud
block.15 = minecraft:ochre_froglight minecraft:verdant_froglight minecraft:pearlescent_froglight
block.16 = minecraft:beacon
block.17 = minecraft:enchanting_table
